### ISSUE TITLE
Display exception

### ISSUE THREAD

**Issue by PlexPt** [MathewSachin/Captura#389] opened 2019-04-01 13:11 UTC
**Describe the bug**
 Display exception

**Screenshots**
 
![image](https://user-images.githubusercontent.com/15922823/55329955-741da800-54c2-11e9-8fbf-09842ddb4803.png)

**Desktop (please complete the following information):**
 - OS:  win 10
 - RAM: 8G
 - CPU:  i7 8086k
 - Graphic Card: 1060
 - Version: last

**Comment by MathewSachin** [comment] 2019-05-06 06:11
Closing this since I cannot reproduce this issue on multiple Windows 10 systems.
Reopen if someone else faces the same issue.

**Closed by MathewSachin** 2019-05-06 06:11 UTC
Labels: bug, cannot reproduce
