### ISSUE TITLE
[Suggestion] Replay recording (to only keep the last x minutes of the recording)

### ISSUE THREAD

**Issue by TheNetStriker** [MathewSachin/Captura#337] opened 2018-12-04 11:26 UTC
Would it be possible to implement some kind of replay recording feature? This would be very handy to continuously record a video to capture problems that only occur from time to time.

When enabled the application should only store the last x Minutes of the recording (maybe directly in Memory) and when the save button is clicked only those last Minutes of video would be saved to a file.

**Comment by MathewSachin** [comment] 2018-12-04 12:19
Duplicate of #182

**Closed by MathewSachin** 2018-12-04 12:19 UTC
