### ISSUE TITLE
Stop + Start causes mouse cursor hang in the console application

### ISSUE THREAD

**Issue by postacik** [MathewSachin/Captura#349] opened 2018-12-22 01:16 UTC
You've created a great application with nice and clean code. Congratulations.

I have a problem on the master branch.

I changed the loop code in the console application like this:

```
                do
                {
                    c = ReadChar();

                    if (c != 'p')
                        continue;

                    //_recordingModel.OnPauseExecute();

                    //if (_recordingModel.RecorderState != RecorderState.Paused)
                    //{
                    //    WriteLine("Resumed");
                    //}

                    WriteLine("Stopping");
                    _recordingModel.StopRecording().Wait();
                    WriteLine("Starting new");
                    _recordingModel.StartRecording(StartOptions.FileName);

                } while (c != 'q');
```

When the user clicks "p", the application stops the current recording and starts a new one.

When I call "capture-cli.exe start", the application starts recording but when I press "p", the mouse cursor hangs and does not move any more until I press "q" and quit application.

But in the WPF application, "Stop" + "Start" action has only a slight pause effect on the mouse cursor. 

Can you tell me how I can solve this problem?

**Comment by MathewSachin** [comment] 2018-12-22 13:16
The problem is happening with the `MouseKeyHook` component. Removing its usage from `RecordingModel.cs Line: 480` will fix the problem you're having. But, then mouse click and keystrokes overlays would not work.

Earlier this problem used to happen every time when recording from console version. The reason being that the `MouseKeyHook` component requires a windows message loop to run. It was fixed by adding a dummy loop.

I don't know why but it seems like this workaround fails when using multiple recordings which in turn create multiple instances of `MouseKeyHook`.

**Comment by postacik** [comment] 2018-12-22 16:12
Thank you very much Mathew. It works with this fix but mouse cursor becomes invisible in the recording, too. Is it possible to get it back?

In the WPF version, you can start and stop recording many times and there is no such issue there. Doesn't that version create multiple instances of `MouseKeyHook`?

**Comment by postacik** [comment] 2018-12-22 16:30
After making the fix, I modified the console version to make 100 recordings,  2 seconds each.

I used ffmpeg:0 codec and recorded both the microphone and the loopback source.

The application memory consumption reached 1 GB after 100 recordings.

Where should I look for memory leaks?

**Comment by MathewSachin** [comment] 2018-12-22 16:33
WPF and console apps are different in that there is no windows message loop in a console application.
I've created a dummy message loop for console version and it works fine for single instance of `MouseKeyHook`. Not sure why it doesn't work for multiple instances though.

If you're asking about mouse cursor and not the click overlay, passing the `--cursor` command-line argument will show cursor.

As for the memory leaks, I'll try to take a look into it and let you know.

**Comment by postacik** [comment] 2018-12-22 16:53
Thanks 👍 
If you can point the important parts of the code which may cause memory leak, I may also have a look into it.

**Comment by MathewSachin** [comment] 2018-12-22 17:30
See my latest commit.
I've set buffers to `null` when `Dispose` functions are called.
This causes GC to free memory sooner.

**Comment by postacik** [comment] 2018-12-22 18:00
I'll test and report the results about the memory leak.

I made other tests with the cli version. I record with the following parameters on a Core i7 laptop with Nvidia graphic card.

ffmpeg:0, vq=40, aq=40, fps=10, mic and speaker recorded, cursor is visible.

With the cli version video freezes somewhere after 30 seconds but audio goes fine.

With the WPF application there seems to be no problem.

Is this normal?

**Comment by postacik** [comment] 2018-12-23 11:51
I tested with the latest commit. Memory leak seems to have gone.

However video still freezes around after 30 seconds.

**Comment by postacik** [comment] 2018-12-23 18:48
Hi Mathew,

I solved the problem like this:

I changed the Application start routine like this:

```
            var context = new ApplicationContext();
            form = new Form();
            context.MainForm = form;

            //Application.Run(new ApplicationContext());
            Application.Run(context);

```

And I changed the StartRecording part like this:
```

 Get["/start-recording"] = parameters =>
            {
                if (ConsoleManager._recordingModel.RecorderState == Captura.Models.RecorderState.NotRecording)
                {
                   ConsoleManager.form.Invoke(new MethodInvoker(delegate
                    {
                        ConsoleManager._recordingModel.StartRecording(null);
                    }));
                    return Response.AsJson(new
                    {
                        result = "Recording started",
                    });
                }
                else
                {
                    return Response.AsJson(new
                    {
                        result = "Recording already in progress",
                    });
                }
            };

```

Now it records event longer records without any freezing problem.

Thank you very much for your help and this great application. 👍

**Closed** 2018-12-24 18:37 UTC
Labels: question
