### ISSUE TITLE
Command line cannot save video 

### ISSUE THREAD

**Issue by andrewang** [MathewSachin/Captura#171] opened 2018-03-05 05:54 UTC
Using V6.0 version, through command line captura start --length 10 --cursor --keys --speaker=0, the countdown ends the command line tool to stop, no video output. The start and end buttons in UI can be recorded and saved, and the win10 I use

**Comment by MathewSachin** [comment] 2018-03-05 06:06
It seems to work fine for the latest development build.

Please test: https://ci.appveyor.com/api/buildjobs/7nccbxne9yhc47c1/artifacts/temp%2FCaptura-Portable.zip

**Comment by MathewSachin** [comment] 2018-04-20 15:57
Closing since unable to reproduce

**Closed by MathewSachin** 2018-04-20 15:57 UTC
