### ISSUE TITLE
FFMpeg exited suddenly while recording

### ISSUE THREAD

**Issue by arjun-g** [MathewSachin/Captura#169] opened 2018-03-04 11:26 UTC
Hi,

Thank you for this great project. I am using Screna in one of my projects. I use RegionProvider, MixedAudioProvider and FFMpegWriter. While recording the FFMpeg exited suddenly without me calling pause or stop method. Though it happened only once I am little bit skeptical on whether this might happen again. What do you think might be the reason for this ?

**Comment by MathewSachin** [comment] 2018-03-04 11:39
I may be able to help if I could see the FFMpeg output log.

**Comment by arjun-g** [comment] 2018-03-04 16:36
These are parameters and ffmpeg output from that session


**Video In Args**

-framerate 15 -f rawvideo -pix_fmt rgb32 -video_size 1920x1080 -i \\\\.\\pipe\\69c1f4f7-1984-471a-b78c-10a4f87b1917

**Video Out Args**

-vcodec libx264 -crf 15 -pix_fmt yuv420p -preset ultrafast -r 15

**Audio In Args**

-f s16le -acodec pcm_s16le -ar 44100 -ac 2 -i \\\\.\\pipe\\035ea88e-3a4b-4872-80c1-ec73683507d7

**Audio Out Args**

-c:a aac -strict -2 -b:a 256k

**FFMPEG stderr output**

ffmpeg version N-90143-gb6652f5100 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 7.3.0 (GCC)
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-amf --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth
libavutil      56.  7.101 / 56.  7.101
libavcodec     58. 12.102 / 58. 12.102
libavformat    58.  9.100 / 58.  9.100
libavdevice    58.  2.100 / 58.  2.100
libavfilter     7. 12.100 /  7. 12.100
libswscale      5.  0.101 /  5.  0.101
libswresample   3.  0.101 /  3.  0.101
libpostproc    55.  0.100 / 55.  0.100
Input #0, rawvideo, from '\\\\.\\pipe\\69c1f4f7-1984-471a-b78c-10a4f87b1917':
Duration: N/A, start: 0.000000, bitrate: 995328 kb/s
Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 1920x1080, 995328 kb/s, 15 tbr, 15 tbn, 15 tbc
Guessed Channel Layout for Input Stream #1.0 : stereo
Input #1, s16le, from '\\\\.\\pipe\\035ea88e-3a4b-4872-80c1-ec73683507d7':
Duration: N/A, bitrate: 1411 kb/s
Stream #1:0: Audio: pcm_s16le, 44100 Hz, stereo, s16, 1411 kb/s
Stream mapping:
Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
Stream #1:0 -> #0:1 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 000001f6c817c640] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 000001f6c817c640] profile Constrained Baseline, level 4.0
[libx264 @ 000001f6c817c640] 264 - core 155 r2901 7d0ff22 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=1 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=15 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=15.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
[s16le @ 000001f6c812d6c0] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
Output #0, mp4, to 'C:\\Users\\KMAYBE~1\\AppData\\Local\\Temp\\932eb05e-35d1-8588-8742-26ace8cf4059\\877a07b7-d63a-e8d9-ef81-7610dd527ffe.mp4':
Metadata:
encoder         : Lavf58.9.100
Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080, q=-1--1, 15 fps, 15360 tbn, 15 tbc
Metadata:
encoder         : Lavc58.12.102 libx264
Side data:
cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 256 kb/s
Metadata:
encoder         : Lavc58.12.102 aac
frame=    1 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
[rawvideo @ 000001f6c8119dc0] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
frame=    8 fps=6.3 q=5.0 size=       0kB time=00:00:00.00 bitrate=5907.7kbits/s speed=5.13e-005x    
frame=    8 fps=0.4 q=5.0 size=       0kB time=00:00:00.00 bitrate=5907.7kbits/s speed=3.35e-006x    
frame=   10 fps=0.3 q=6.0 size=       0kB time=00:00:00.13 bitrate=   2.9kbits/s speed=0.00466x    
frame=   11 fps=0.3 q=5.0 size=     256kB time=00:00:00.20 bitrate=10484.3kbits/s speed=0.0048x    
frame=   12 fps=0.3 q=4.0 size=     256kB time=00:00:00.26 bitrate=7863.8kbits/s speed=0.00574x    
frame=   13 fps=0.3 q=3.0 size=     256kB time=00:00:00.33 bitrate=6291.4kbits/s speed=0.00651x    
frame=   14 fps=0.2 q=5.0 size=     256kB time=00:00:00.40 bitrate=5243.0kbits/s speed=0.00632x    
frame=   15 fps=0.2 q=4.0 size=     256kB time=00:00:00.46 bitrate=4494.1kbits/s speed=0.00731x    
frame=   17 fps=0.3 q=3.0 size=     512kB time=00:00:00.60 bitrate=6990.4kbits/s speed=0.00932x    
frame=   28 fps=0.4 q=3.0 size=     512kB time=00:00:01.33 bitrate=3145.9kbits/s speed=0.0206x    
frame=   39 fps=0.6 q=3.0 size=     768kB time=00:00:02.06 bitrate=3044.3kbits/s speed=0.0316x    
frame=   44 fps=0.7 q=3.0 size=     768kB time=00:00:02.40 bitrate=2621.5kbits/s speed=0.0364x    
frame=   50 fps=0.7 q=3.0 size=     768kB time=00:00:02.80 bitrate=2247.0kbits/s speed=0.042x    
frame=   54 fps=0.8 q=3.0 size=    1024kB time=00:00:03.06 bitrate=2735.5kbits/s speed=0.0456x    
frame=   71 fps=1.0 q=3.0 size=    1280kB time=00:00:04.20 bitrate=2495.0kbits/s speed=0.0617x    
frame=   75 fps=1.1 q=3.0 size=    1280kB time=00:00:04.46 bitrate=2347.6kbits/s speed=0.065x    
frame=   81 fps=1.2 q=3.0 size=    1280kB time=00:00:04.86 bitrate=2154.7kbits/s speed=0.0703x    
frame=   87 fps=1.2 q=3.0 size=    1280kB time=00:00:05.26 bitrate=1991.0kbits/s speed=0.0744x    
frame=   94 fps=1.3 q=3.0 size=    1536kB time=00:00:05.73 bitrate=2194.0kbits/s speed=0.0805x    
frame=  103 fps=1.4 q=3.0 size=    1536kB time=00:00:06.33 bitrate=1986.8kbits/s speed=0.0879x    
frame=  105 fps=1.4 q=3.0 size=    1536kB time=00:00:06.46 bitrate=1945.9kbits/s speed=0.0888x    
frame=  108 fps=1.5 q=3.0 size=    1792kB time=00:00:06.66 bitrate=2202.0kbits/s speed=0.09x    
frame=  110 fps=1.5 q=3.0 size=    1792kB time=00:00:06.80 bitrate=2158.9kbits/s speed=0.0911x    
frame=  117 fps=1.6 q=3.0 size=    1792kB time=00:00:07.26 bitrate=2019.9kbits/s speed=0.0963x    
frame=  122 fps=1.6 q=3.0 size=    1792kB time=00:00:07.60 bitrate=1931.6kbits/s speed=0.0971x    
frame=  133 fps=1.7 q=3.0 size=    2048kB time=00:00:08.33 bitrate=2012.7kbits/s speed=0.106x    
frame=  136 fps=1.7 q=3.0 size=    2048kB time=00:00:08.53 bitrate=1966.1kbits/s speed=0.106x    
frame=  145 fps=1.8 q=3.0 size=    2304kB time=00:00:09.13 bitrate=2066.6kbits/s speed=0.113x    
frame=  147 fps=1.8 q=3.0 size=    2304kB time=00:00:09.26 bitrate=2036.8kbits/s speed=0.114x    
frame=  148 fps=1.8 q=3.0 size=    2304kB time=00:00:09.33 bitrate=2022.1kbits/s speed=0.113x    
frame=  164 fps=2.0 q=3.0 size=    2560kB time=00:00:10.40 bitrate=2016.0kbits/s speed=0.125x    
frame=  186 fps=2.2 q=3.0 size=    2816kB time=00:00:11.86 bitrate=1944.0kbits/s speed=0.142x    
frame=  198 fps=2.4 q=3.0 size=    2816kB time=00:00:12.66 bitrate=1821.2kbits/s speed=0.151x    
frame=  213 fps=2.5 q=3.0 size=    3072kB time=00:00:13.66 bitrate=1841.4kbits/s speed=0.162x    
frame=  231 fps=2.7 q=3.0 size=    3328kB time=00:00:14.86 bitrate=1833.9kbits/s speed=0.175x    
frame=  240 fps=2.8 q=3.0 size=    3584kB time=00:00:15.46 bitrate=1898.3kbits/s speed=0.181x    
frame=  251 fps=2.9 q=3.0 size=    3584kB time=00:00:16.20 bitrate=1812.4kbits/s speed=0.188x    
frame=  258 fps=3.0 q=5.0 size=    3840kB time=00:00:16.66 bitrate=1887.5kbits/s speed=0.192x    
frame=  277 fps=3.2 q=3.0 size=    4352kB time=00:00:17.93 bitrate=1988.0kbits/s speed=0.205x    
frame=  291 fps=3.3 q=3.0 size=    4352kB time=00:00:18.86 bitrate=1889.7kbits/s speed=0.215x    
frame=  307 fps=3.5 q=3.0 size=    4352kB time=00:00:19.93 bitrate=1788.6kbits/s speed=0.226x    
frame=  312 fps=3.5 q=3.0 size=    4352kB time=00:00:20.26 bitrate=1759.1kbits/s speed=0.228x    
frame=  323 fps=3.6 q=3.0 size=    4352kB time=00:00:21.00 bitrate=1697.7kbits/s speed=0.235x    
frame=  336 fps=3.7 q=3.0 size=    4608kB time=00:00:21.86 bitrate=1726.3kbits/s speed=0.243x    
frame=  361 fps=4.0 q=4.0 size=    4608kB time=00:00:23.53 bitrate=1604.1kbits/s speed=0.26x    
frame=  383 fps=4.2 q=3.0 size=    4608kB time=00:00:25.00 bitrate=1510.0kbits/s speed=0.275x    
frame=  403 fps=4.4 q=3.0 size=    4608kB time=00:00:26.33 bitrate=1433.5kbits/s speed=0.286x    
frame=  410 fps=4.4 q=-1.0 Lsize=    4848kB time=00:00:27.26 bitrate=1456.6kbits/s speed=0.296x    
video:4001kB audio:835kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.243641%
[libx264 @ 000001f6c817c640] frame I:2     Avg QP: 6.00  size:411910
[libx264 @ 000001f6c817c640] frame P:408   Avg QP: 3.34  size:  8022
[libx264 @ 000001f6c817c640] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 000001f6c817c640] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 000001f6c817c640] mb P  I16..4:  0.4%  0.0%  0.0%  P16..4: 19.9%  0.0%  0.0%  0.0%  0.0%    skip:79.6%
[libx264 @ 000001f6c817c640] coded y,uvDC,uvAC intra: 42.8% 41.2% 39.6% inter: 8.7% 0.4% 0.4%
[libx264 @ 000001f6c817c640] i16 v,h,dc,p: 67% 28%  2%  3%
[libx264 @ 000001f6c817c640] i8c dc,h,v,p: 35% 54%  8%  3%
[libx264 @ 000001f6c817c640] kb/s:1199.07
[libx264 @ 000001f6c817c640] kb/s:1199.07
[aac @ 000001f6c817f400] Qavg: 201.461

**Comment by MathewSachin** [comment] 2018-03-04 17:05
Seems like ffmpeg is unable to process the frames as fast as 15fps for the quality.
Try increasing the crf value to something around 25 to 28.

If that still doesn't work, try with the custom version of Screna in this repository which is better in performance.

**Comment by MathewSachin** [comment] 2018-04-20 16:01
Closing since unable to reproduce.

**Closed by MathewSachin** 2018-04-20 16:01 UTC
