### ISSUE TITLE
Audio is not recording with Video file. 

### ISSUE THREAD

**Issue by SaddamBInSyed** [MathewSachin/Captura#370] opened 2019-02-18 08:24 UTC
**Describe the bug**
Audio is not recording with Video file

How to add audio recording into Video file? please advise the steps to change the code if not implemented in this version.

**Comment by MathewSachin** [comment] 2019-02-19 11:11
It is already implemented.

**More Information Needed**
Are you referring to the UI or console version?
Are you using latest release or building from source code?

**Comment by SaddamBInSyed** [comment] 2019-02-19 13:40
using 8.0.0 build source.

audio is not mixing with Camera video. BUT only mixing with desktop record video.

please advise.

**Comment by MathewSachin** [comment] 2019-02-19 14:25
Audio not mixing with Webcam video but with Desktop video is the intended behaviour of Captura.

This issue seems to be a duplicate of #344 opened by you. So, I'm closing this issue.
If you want further help, comment on that issue instead of opening a new one.

**Note:** From the next time you open an issue, please be clear with what you need to convey. The issue title and the message were misleading.

**Closed by MathewSachin** 2019-02-19 14:25 UTC
