### ISSUE TITLE
Please impress OK or "back button" for this screen.

### ISSUE THREAD

**Issue by saurabhdua82** [MathewSachin/Captura#267] opened 2018-09-20 09:26 UTC
Hello Sachin !

Please refer to the following screen representation & help introduce an OK or a "back button" for this very screen.

It doesn't look nice to merely terminate this window by clicking 'X' here !

You must reflect >> "All set to go" >> OK after the FFMpeg download completion.

Thus, there'll be a "Warm transfer" for users of Captura.

Thanks.

![zm5uwds 1](https://user-images.githubusercontent.com/23373249/45808967-af097c80-bce4-11e8-8bff-14bc1139dbd5.jpg)

**Comment by MathewSachin** [comment] 2018-09-20 09:33
This is a duplicate of #202 reported by you and was resolved too. The button changes to Finish after download. Please check the latest pre-release version.

**Closed by MathewSachin** 2018-09-20 09:33 UTC
